name: mosfet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: TitilliumWebRegular
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: TitilliumWebSemiBold
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
